SET DEFINE OFF;

CREATE TABLE location (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, external_id VARCHAR2(255) NOT NULL, latitude DECIMAL(10, 6), longitude DECIMAL(10, 6), address_line_1 VARCHAR2(255), address_line_2 VARCHAR2(255), post_code VARCHAR2(255), city VARCHAR2(255), state VARCHAR2(50), country VARCHAR2(255), complete_address VARCHAR2(255), source VARCHAR2(255) NOT NULL, inserted_at TIMESTAMP NOT NULL, updated_at TIMESTAMP, CONSTRAINT PK_LOCATION PRIMARY KEY (id));

CREATE TABLE merchant (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, external_id VARCHAR2(255) NOT NULL, name VARCHAR2(255) NOT NULL, logo VARCHAR2(255), website VARCHAR2(255), location_id INTEGER, source VARCHAR2(255) NOT NULL, inserted_at TIMESTAMP NOT NULL, updated_at TIMESTAMP, CONSTRAINT PK_MERCHANT PRIMARY KEY (id), CONSTRAINT fk_location_id FOREIGN KEY (location_id) REFERENCES location(id));

CREATE TABLE enriched_transaction (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, arrangement_id VARCHAR2(36) NOT NULL, transaction_id VARCHAR2(36) NOT NULL, category_id INTEGER NOT NULL, merchant_id INTEGER, description VARCHAR2(255) NOT NULL, source VARCHAR2(255) NOT NULL, inserted_at TIMESTAMP NOT NULL, CONSTRAINT PK_ENRICHED_TRANSACTION PRIMARY KEY (id), CONSTRAINT fk_merchant_id FOREIGN KEY (merchant_id) REFERENCES merchant(id));

CREATE TABLE user_transaction_override (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, transaction_id VARCHAR2(36) NOT NULL, category_id INTEGER NOT NULL, inserted_at TIMESTAMP NOT NULL, updated_at TIMESTAMP, CONSTRAINT PK_USER_TRANSACTION_OVERRIDE PRIMARY KEY (id));

CREATE INDEX ix_enriched_transaction_transaction_id ON enriched_transaction(transaction_id);

CREATE UNIQUE INDEX uq_merchant_external_id_source ON merchant(external_id, source);

CREATE INDEX ix_user_transaction_override_transaction_id ON user_transaction_override(transaction_id);

CREATE INDEX ix_location_external_id_source ON location(external_id, source);

