server:
  port: 9915

# API Registry client configuration
eureka:
  instance:
    metadata-map:
      public: true
      role: live
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/registry/eureka/

# Configure Internal JWT handler
sso:
  jwt:
    internal:
      signature:
        key:
          type: ENV
          value: SIG_SECRET_KEY

# Spring health monitoring
management:
  health:
    jms:
     enabled: false


# Transferwise
transferwise:
  url:
    base: https://api.sandbox.transferwise.tech/v1
    rates: ${transferwise.url.base}/rates?source={source}&target={target}&from={form}&to={to}
  api-key: 11cacd02-d055-4295-8ecc-90bfe1929c7a